// flow-typed signature: 2a0086809a7579dc504d1c9b89b9dea7
// flow-typed version: <<STUB>>/jest-serializer-enzyme_v1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-serializer-enzyme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-serializer-enzyme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-serializer-enzyme/test/mount.test' {
  declare module.exports: any;
}

declare module 'jest-serializer-enzyme/test/shallow.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-serializer-enzyme/index' {
  declare module.exports: $Exports<'jest-serializer-enzyme'>;
}
declare module 'jest-serializer-enzyme/index.js' {
  declare module.exports: $Exports<'jest-serializer-enzyme'>;
}
declare module 'jest-serializer-enzyme/test/mount.test.js' {
  declare module.exports: $Exports<'jest-serializer-enzyme/test/mount.test'>;
}
declare module 'jest-serializer-enzyme/test/shallow.test.js' {
  declare module.exports: $Exports<'jest-serializer-enzyme/test/shallow.test'>;
}
