// flow-typed signature: ae11214b23db6e99cc2c52e109e63ea4
// flow-typed version: <<STUB>>/preact-compat_v3.16.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-compat'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-compat' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-compat/dist/preact-compat.es' {
  declare module.exports: any;
}

declare module 'preact-compat/dist/preact-compat' {
  declare module.exports: any;
}

declare module 'preact-compat/dist/preact-compat.min' {
  declare module.exports: any;
}

declare module 'preact-compat/karma.conf' {
  declare module.exports: any;
}

declare module 'preact-compat/legacy' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/create-react-class' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/ReactComponentWithPureRenderMixin' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/ReactFragment' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/ReactMount' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/ReactPerf' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/ReactTransitionEvents' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/ReactTransitionGroup' {
  declare module.exports: any;
}

declare module 'preact-compat/lib/update' {
  declare module.exports: any;
}

declare module 'preact-compat/rollup.config' {
  declare module.exports: any;
}

declare module 'preact-compat/server' {
  declare module.exports: any;
}

declare module 'preact-compat/src/index' {
  declare module.exports: any;
}

declare module 'preact-compat/test/component' {
  declare module.exports: any;
}

declare module 'preact-compat/test/index' {
  declare module.exports: any;
}

declare module 'preact-compat/test/jsx' {
  declare module.exports: any;
}

declare module 'preact-compat/test/legacy' {
  declare module.exports: any;
}

declare module 'preact-compat/test/lib/ReactComponentWithPureRenderMixin' {
  declare module.exports: any;
}

declare module 'preact-compat/test/lib/ReactFragment' {
  declare module.exports: any;
}

declare module 'preact-compat/test/lib/ReactMount' {
  declare module.exports: any;
}

declare module 'preact-compat/test/lib/ReactTransitionEvents' {
  declare module.exports: any;
}

declare module 'preact-compat/test/lib/ReactTransitionGroup' {
  declare module.exports: any;
}

declare module 'preact-compat/test/lib/update' {
  declare module.exports: any;
}

declare module 'preact-compat/test/svg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-compat/dist/preact-compat.es.js' {
  declare module.exports: $Exports<'preact-compat/dist/preact-compat.es'>;
}
declare module 'preact-compat/dist/preact-compat.js' {
  declare module.exports: $Exports<'preact-compat/dist/preact-compat'>;
}
declare module 'preact-compat/dist/preact-compat.min.js' {
  declare module.exports: $Exports<'preact-compat/dist/preact-compat.min'>;
}
declare module 'preact-compat/karma.conf.js' {
  declare module.exports: $Exports<'preact-compat/karma.conf'>;
}
declare module 'preact-compat/legacy.js' {
  declare module.exports: $Exports<'preact-compat/legacy'>;
}
declare module 'preact-compat/lib/create-react-class.js' {
  declare module.exports: $Exports<'preact-compat/lib/create-react-class'>;
}
declare module 'preact-compat/lib/ReactComponentWithPureRenderMixin.js' {
  declare module.exports: $Exports<'preact-compat/lib/ReactComponentWithPureRenderMixin'>;
}
declare module 'preact-compat/lib/ReactFragment.js' {
  declare module.exports: $Exports<'preact-compat/lib/ReactFragment'>;
}
declare module 'preact-compat/lib/ReactMount.js' {
  declare module.exports: $Exports<'preact-compat/lib/ReactMount'>;
}
declare module 'preact-compat/lib/ReactPerf.js' {
  declare module.exports: $Exports<'preact-compat/lib/ReactPerf'>;
}
declare module 'preact-compat/lib/ReactTransitionEvents.js' {
  declare module.exports: $Exports<'preact-compat/lib/ReactTransitionEvents'>;
}
declare module 'preact-compat/lib/ReactTransitionGroup.js' {
  declare module.exports: $Exports<'preact-compat/lib/ReactTransitionGroup'>;
}
declare module 'preact-compat/lib/update.js' {
  declare module.exports: $Exports<'preact-compat/lib/update'>;
}
declare module 'preact-compat/rollup.config.js' {
  declare module.exports: $Exports<'preact-compat/rollup.config'>;
}
declare module 'preact-compat/server.js' {
  declare module.exports: $Exports<'preact-compat/server'>;
}
declare module 'preact-compat/src/index.js' {
  declare module.exports: $Exports<'preact-compat/src/index'>;
}
declare module 'preact-compat/test/component.js' {
  declare module.exports: $Exports<'preact-compat/test/component'>;
}
declare module 'preact-compat/test/index.js' {
  declare module.exports: $Exports<'preact-compat/test/index'>;
}
declare module 'preact-compat/test/jsx.js' {
  declare module.exports: $Exports<'preact-compat/test/jsx'>;
}
declare module 'preact-compat/test/legacy.js' {
  declare module.exports: $Exports<'preact-compat/test/legacy'>;
}
declare module 'preact-compat/test/lib/ReactComponentWithPureRenderMixin.js' {
  declare module.exports: $Exports<'preact-compat/test/lib/ReactComponentWithPureRenderMixin'>;
}
declare module 'preact-compat/test/lib/ReactFragment.js' {
  declare module.exports: $Exports<'preact-compat/test/lib/ReactFragment'>;
}
declare module 'preact-compat/test/lib/ReactMount.js' {
  declare module.exports: $Exports<'preact-compat/test/lib/ReactMount'>;
}
declare module 'preact-compat/test/lib/ReactTransitionEvents.js' {
  declare module.exports: $Exports<'preact-compat/test/lib/ReactTransitionEvents'>;
}
declare module 'preact-compat/test/lib/ReactTransitionGroup.js' {
  declare module.exports: $Exports<'preact-compat/test/lib/ReactTransitionGroup'>;
}
declare module 'preact-compat/test/lib/update.js' {
  declare module.exports: $Exports<'preact-compat/test/lib/update'>;
}
declare module 'preact-compat/test/svg.js' {
  declare module.exports: $Exports<'preact-compat/test/svg'>;
}
